application: hackerdojo-kudos
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: shared/static/favicon.ico
  upload: shared/static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /shared/static
  static_dir: shared/static
- url: /static
  static_dir: static
- url: .*
  script: main.py
